name: flutter_blue_plus_platform_interface
description: A common platform interface for the flutter_blue_plus plugin.
version: 4.0.2
homepage: https://github.com/chipweinberger/flutter_blue_plus

publish_to: none'

environment:
  sdk: ^3.0.0
  flutter: '>=3.7.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
